repo_url: https://github.com/ssdq/wiki
site_name: Serious Sam Done Quick Wiki
site_url: https://wiki.ssdq.org/
theme:
  name: windmill
extra:
  logo: images/logo.svg
extra_css:
  - 'stylesheets/style.css'
extra_javascript:
  - 'scripts/youtube-embeds.js'
markdown_extensions:
  - toc:
      permalink: true
